import tkinter as tk
from functools import partial
def add(result,n1,n2):
	a=(n1.get())
	b=(n2.get())
	c=float(a)+float(b)
	result.config(text="Sum of numbers is %d" % c)
def sub(result,n1,n2):
	a=(n1.get())
	b=(n2.get())
	c=float(a)-float(b)
	result.config(text="Subtraction of numbers is %d" % c)
def mul(result,n1,n2):
	a=(n1.get())
	b=(n2.get())
	c=float(a)*float(b)
	result.config(text="Product of numbers is %d" % c)
def div(result,n1,n2):
	a=(n1.get())
	b=(n2.get())
	c=float(a)/float(b)
	result.config(text="Division of numbers is %d" % c)
def clear():
    num1.delete(0,30)
    num2.delete(0,30)
    result.config(text=" ")
root=tk.Tk()
root.geometry('400x200+100+200')
root.title("Calculator")
label=tk.Label(root,text="Number 1 :",fg="blue")
label.grid(row=1,column=0)
label1=tk.Label(root,text="Number 2 :",fg="blue")
label1.grid(row=2,column=0)
number1=tk.StringVar()
number2=tk.StringVar()
num1=tk.Entry(root,textvariable=number1)
num1.grid(row=1,column=1)
num2=tk.Entry(root,textvariable=number2)
num2.grid(row=2,column=1)
result=tk.Label(root,fg="blue")
result.grid(row=8,column=1)
add=partial(add,result,number1,number2)
addition=tk.Button(root,text="Add",width=6,command=add)
addition.grid(row=5,column=0)
sub=partial(sub,result,number1,number2)
subtraction=tk.Button(root,text="Subtract",width=8,command=sub)
subtraction.grid(row=5,column=1)
mul=partial(mul,result,number1,number2)
multiplication=tk.Button(root,text="Multiply",width=8,command=mul)
multiplication.grid(row=6,column=0,padx=5)
div=partial(div,result,number1,number2)
division=tk.Button(root,text="Divide",width=7,command=div)
division.grid(row=6,column=1,padx=3)
clr=tk.Button(root,text="Clear",command=clear)
clr.grid(row=6,column=2)
root.mainloop()
